#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
test_root="$(mktemp -d)"
trap 'rm -rf "$test_root"' EXIT
mkdir -p "$test_root/bin"

script="$repo_root/scripts/verify-production-schema-semantic-drift.sh"

write_supabase() {
  cat > "$test_root/bin/supabase"
  chmod +x "$test_root/bin/supabase"
}

run_check() {
  local out_file="$1"
  local err_file="$2"
  SUPABASE_DB_URL='postgresql://readonly:test@example.invalid:5432/postgres' \
    PATH="$test_root/bin:$PATH" \
    bash "$script" "$out_file" "$err_file"
}

# 1. Comments, whitespace and known session-only preamble are not schema drift.
write_supabase <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
[[ "$1 $2" == "db diff" ]]
cat <<'SQL'
-- Diff generated by pg-schema-diff

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SELECT pg_catalog.set_config('search_path', '', false);
  -- another informational comment
SQL
MOCK
run_check "$test_root/no-drift.sql" "$test_root/no-drift.stderr" >/dev/null
test "$(cat "$test_root/no-drift.sql")" = 'none'

# 2. Actual DDL survives normalization and fails closed.
write_supabase <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
[[ "$1 $2" == "db diff" ]]
cat <<'SQL'
-- harmless header
SET statement_timeout = 0;
ALTER TABLE public.orders ADD COLUMN unexpected_column text;
SQL
MOCK
if run_check "$test_root/drift.sql" "$test_root/drift.stderr" >"$test_root/drift.out" 2>"$test_root/drift.fail"; then
  echo 'expected semantic drift check to fail when DDL is emitted' >&2
  exit 1
fi
grep -q '^ALTER TABLE public.orders ADD COLUMN unexpected_column text;$' "$test_root/drift.sql"
if grep -q '^--\|^SET statement_timeout' "$test_root/drift.sql"; then
  echo 'semantic drift evidence retained non-structural boilerplate' >&2
  exit 1
fi
grep -q '^ACTUAL_SCHEMA_DRIFT:' "$test_root/drift.fail"

# 3. GRANT/REVOKE and other schema-bearing statements are never normalized away.
write_supabase <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
[[ "$1 $2" == "db diff" ]]
printf '%s\n' 'GRANT SELECT ON TABLE public.orders TO authenticated;'
MOCK
if run_check "$test_root/grant-drift.sql" "$test_root/grant-drift.stderr" >/dev/null 2>&1; then
  echo 'expected semantic drift check to fail for privilege drift' >&2
  exit 1
fi
grep -q '^GRANT SELECT ON TABLE public.orders TO authenticated;$' "$test_root/grant-drift.sql"

# 4. CLI failures propagate and preserve stderr instead of being misclassified
# as schema equality.
write_supabase <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
echo 'mock remote connection failure' >&2
exit 7
MOCK
set +e
run_check "$test_root/cli-fail.sql" "$test_root/cli-fail.stderr" >/dev/null 2>"$test_root/cli-fail.wrapper"
status=$?
set -e
test "$status" -eq 7
grep -q 'mock remote connection failure' "$test_root/cli-fail.stderr"
grep -q 'SEMANTIC SCHEMA DRIFT CHECK FAILED: supabase db diff exited 7' "$test_root/cli-fail.wrapper"

# 5. Missing production connection evidence is a hard failure before invoking
# the CLI.
set +e
PATH="$test_root/bin:$PATH" SUPABASE_DB_URL='' bash "$script" \
  "$test_root/missing-url.sql" "$test_root/missing-url.stderr" >/dev/null 2>&1
status=$?
set -e
test "$status" -ne 0

echo 'verify-production-schema-semantic-drift.sh: all cases passed'
