#!/usr/bin/env bash
# Verify supabase/.env.preview decrypts with the governed preview dotenvx authority.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"

preview_file="supabase/.env.preview"
keys_file="supabase/.env.keys"
script_dir="$(dirname "$0")"
dotenvx_version="1.44.1"
production_ref="${PRODUCTION_PROJECT_REF:-tcxvcatsqqertcnycuop}"

[[ -f "$preview_file" ]] || exit 1
grep -Fq "encrypted:" "$preview_file" || exit 1

# Prefer the explicit GitHub-scoped key only when one is deliberately supplied.
# Otherwise re-fetch the current production-owned key instead of trusting a
# pre-existing local .env.keys file, which may have been generated by dotenvx
# under an obsolete authority.
if [[ -n "${PREVIEW_DOTENV_PRIVATE_KEY:-}" ]]; then
  umask 077
  mkdir -p supabase
  printf 'DOTENV_PRIVATE_KEY_PREVIEW=%s\n' "$PREVIEW_DOTENV_PRIVATE_KEY" > "$keys_file"
  echo "::add-mask::${PREVIEW_DOTENV_PRIVATE_KEY}" >&2
elif [[ -n "${SUPABASE_ACCESS_TOKEN:-}" ]]; then
  resolved="$(PRODUCTION_PROJECT_REF="$production_ref" \
    SUPABASE_ACCESS_TOKEN="$SUPABASE_ACCESS_TOKEN" \
    python3 "$script_dir/fetch-production-dotenv-private-key.py" 2>/dev/null || true)"
  [[ -n "$resolved" ]] || exit 1
  umask 077
  mkdir -p supabase
  printf 'DOTENV_PRIVATE_KEY_PREVIEW="%s"\n' "$resolved" > "$keys_file"
  echo "::add-mask::$resolved" >&2
fi

[[ -s "$keys_file" ]] || exit 1

npx --yes "@dotenvx/dotenvx@${dotenvx_version}" get GEMINI_API_KEY \
  -f "$preview_file" --stdout >/dev/null 2>&1
