-- Historical production-ledger compatibility stub.
-- The support ticket tables are already represented by the canonical production
-- schema baseline at 20260723161256.
-- This duplicate reconciliation version intentionally contains no executable SQL.
