-- Historical production-ledger compatibility stub.
-- Production version: 20260514185829
-- Production name: add_payment_proof_audit_columns_to_order_payments
-- Schema effect is represented by the squashed baseline at 20260723161256.
-- This file intentionally contains no executable SQL.
