-- Historical production-ledger compatibility stub.
-- Production version: 20260604133321
-- Production name: wa_sprint9_sales_order_draft_submit_review_atomic_rpc
-- Schema effect is represented by the squashed baseline at 20260723161256.
-- This file intentionally contains no executable SQL.
