-- Historical production-ledger compatibility stub.
-- Production version: 20260604142330
-- Production name: wa_sprint9_sales_order_draft_extraction_version_rpc
-- Schema effect is represented by the squashed baseline at 20260723161256.
-- This file intentionally contains no executable SQL.
