import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const outDir='artifacts/step1-certification', REDACTED='[REDACTED]', sourceRunner='scripts/step1-certification/run.mjs', generatedRunner='scripts/step1-certification/.generated-run.mjs';
function secretVariants(dbUrl=''){const v=new Set();if(dbUrl)v.add(dbUrl);try{const p=new URL(dbUrl);if(p.password){v.add(p.password);try{v.add(decodeURIComponent(p.password));}catch{}}if(p.username)v.add(`${p.username}:${p.password}`);}catch{}return[...v].filter(Boolean).sort((a,b)=>b.length-a.length);}
function redact(value,dbUrl=process.env.SUPABASE_DB_URL??''){let t=String(value??'');for(const s of secretVariants(dbUrl))t=t.split(s).join(REDACTED);return t.replace(/postgres(?:ql)?:\/\/[^\s'"`<>]+/gi,'postgresql://[REDACTED]');}
function sanitizeTree(dir,dbUrl){if(!existsSync(dir))return;for(const n of readdirSync(dir)){const p=join(dir,n),i=statSync(p);if(i.isDirectory())sanitizeTree(p,dbUrl);else if(i.isFile()){const o=readFileSync(p,'utf8'),c=redact(o,dbUrl);if(c!==o)writeFileSync(p,c,{mode:0o600});}}}
function assertNoSecret(dir,dbUrl){if(!existsSync(dir))return;const vs=secretVariants(dbUrl);for(const n of readdirSync(dir)){const p=join(dir,n),i=statSync(p);if(i.isDirectory())assertNoSecret(p,dbUrl);else if(i.isFile()){const c=readFileSync(p,'utf8');for(const s of vs)if(c.includes(s))throw new Error(`Credential redaction regression in ${p}`);if(/postgres(?:ql)?:\/\/[^\s'"`<>]+/i.test(c))throw new Error(`Database URI redaction regression in ${p}`);}}}
function selfTest(){const s='SENTINEL_DB_PASSWORD_DO_NOT_LEAK',f=`postgresql://postgres.test:${s}%40encoded@aws-1-ap-south-1.pooler.supabase.com:5432/postgres`,sample=`failure: Command failed: psql ${f}\npassword=${s}@encoded`,c=redact(sample,f);if(c.includes(s)||c.includes(f)||/postgres(?:ql)?:\/\/[^\s'"`<>]+/i.test(c))throw new Error('Credential redaction self-test failed');mkdirSync(outDir,{recursive:true});const p=join(outDir,'redaction-self-test.txt');writeFileSync(p,sample,{mode:0o600});sanitizeTree(outDir,f);assertNoSecret(outDir,f);console.log('PASS: certification credential redaction self-test');}
function prepareIsolatedRunner(){writeFileSync(generatedRunner,readFileSync(sourceRunner,'utf8'),{mode:0o600});}
if(process.argv.includes('--self-test')){selfTest();process.exit(0);}const dbUrl=process.env.SUPABASE_DB_URL??'';prepareIsolatedRunner();const result=spawnSync(process.execPath,[generatedRunner],{env:process.env,encoding:'utf8',stdio:['ignore','pipe','pipe']});try{sanitizeTree(outDir,dbUrl);assertNoSecret(outDir,dbUrl);}catch(error){rmSync(outDir,{recursive:true,force:true});throw error;}finally{rmSync(generatedRunner,{force:true});}if(result.stdout)process.stdout.write(redact(result.stdout,dbUrl));if(result.stderr)process.stderr.write(redact(result.stderr,dbUrl));if(result.error)process.stderr.write(`${redact(result.error.message,dbUrl)}\n`);if(result.status!==0){console.error(`Step 1 staging certification failed with exit code ${result.status??1}; credentials redacted.`);process.exit(result.status??1);}console.log('PASS: certification process-boundary credential redaction verified');
