import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const outDir='artifacts/step1-certification', REDACTED='[REDACTED]', sourceRunner='scripts/step1-certification/run.mjs', generatedRunner='scripts/step1-certification/.generated-run.mjs';
function secretVariants(dbUrl=''){const v=new Set();if(dbUrl)v.add(dbUrl);try{const p=new URL(dbUrl);if(p.password){v.add(p.password);try{v.add(decodeURIComponent(p.password));}catch{}}if(p.username)v.add(`${p.username}:${p.password}`);}catch{}return[...v].filter(Boolean).sort((a,b)=>b.length-a.length);}
function redact(value,dbUrl=process.env.SUPABASE_DB_URL??''){let t=String(value??'');for(const s of secretVariants(dbUrl))t=t.split(s).join(REDACTED);return t.replace(/postgres(?:ql)?:\/\/[^\s'"`<>]+/gi,'postgresql://[REDACTED]');}
function sanitizeTree(dir,dbUrl){if(!existsSync(dir))return;for(const n of readdirSync(dir)){const p=join(dir,n),i=statSync(p);if(i.isDirectory())sanitizeTree(p,dbUrl);else if(i.isFile()){const o=readFileSync(p,'utf8'),c=redact(o,dbUrl);if(c!==o)writeFileSync(p,c,{mode:0o600});}}}
function assertNoSecret(dir,dbUrl){if(!existsSync(dir))return;const vs=secretVariants(dbUrl);for(const n of readdirSync(dir)){const p=join(dir,n),i=statSync(p);if(i.isDirectory())assertNoSecret(p,dbUrl);else if(i.isFile()){const c=readFileSync(p,'utf8');for(const s of vs)if(c.includes(s))throw new Error(`Credential redaction regression in ${p}`);if(/postgres(?:ql)?:\/\/[^\s'"`<>]+/i.test(c))throw new Error(`Database URI redaction regression in ${p}`);}}}
function selfTest(){const s='SENTINEL_DB_PASSWORD_DO_NOT_LEAK',f=`postgresql://postgres.test:${s}%40encoded@aws-1-ap-south-1.pooler.supabase.com:5432/postgres`,sample=`failure: Command failed: psql ${f}\npassword=${s}@encoded`,c=redact(sample,f);if(c.includes(s)||c.includes(f)||/postgres(?:ql)?:\/\/[^\s'"`<>]+/i.test(c))throw new Error('Credential redaction self-test failed');mkdirSync(outDir,{recursive:true});const p=join(outDir,'redaction-self-test.txt');writeFileSync(p,sample,{mode:0o600});sanitizeTree(outDir,f);assertNoSecret(outDir,f);console.log('PASS: certification credential redaction self-test');}
function prepareIsolatedRunner(){let g=readFileSync(sourceRunner,'utf8');const fg="values(:'company',:'prefix','07AACCC0000A1Z5','New Delhi','approved','prepaid');",ug="values(:'company',:'prefix','07AACCC'||substr(md5(:'prefix'),1,4)||'A1Z5','New Delhi','approved','prepaid');";if(!g.includes(fg))throw new Error('Certification runner GST fixture signature changed; refusing unsafe runtime rewrite');g=g.replace(fg,ug);
const oc='insert into public.orders(id,company_id,status,order_number,sales_order_value,advance_required,advance_paid,payment_status,payment_cleared,final_invoice_url,order_origin)',oct=oc.slice(0,-1)+',tracking_token)',av="(:'authority_order',:'company','submitted',:'prefix'||'-AUTH',100,30,30,'advance_paid',false,'https://example.invalid/invoice','LEGACY_ERP'),",avt="(:'authority_order',:'company','submitted',:'prefix'||'-AUTH',100,30,1000,'advance_paid',false,'https://example.invalid/invoice','LEGACY_ERP',md5(:'prefix'||'-AUTH'))," ,cv="(:'carton_order',:'company','cleared_for_dispatch',:'prefix'||'-CARTON',100,0,100,'paid',true,'https://example.invalid/invoice','LEGACY_ERP');",cvt="(:'carton_order',:'company','cleared_for_dispatch',:'prefix'||'-CARTON',100,0,100,'paid',true,'https://example.invalid/invoice','LEGACY_ERP',md5(:'prefix'||'-CARTON'));";for(const s of[oc,av,cv])if(!g.includes(s))throw new Error('Certification runner order fixture signature changed; refusing unsafe runtime rewrite');g=g.replace(oc,oct).replace(av,avt).replace(cv,cvt);
const di='insert into public.sales_order_drafts(id,packet_id,extraction_request_key,status,company_id,company_name,readiness_overall_score,readiness_dimensions,original_whatsapp_text,created_by,updated_by)',dip=`with cert_contact as (\n        insert into public.whatsapp_contacts(phone_number) values (substr(md5(:'draft'),1,20)) returning id\n      ), cert_packet as (\n        insert into public.whatsapp_message_packets(contact_id,stitched_content,first_message_at,last_message_at)\n        select id,'{}'::jsonb,now(),now() from cert_contact returning id\n      )\n      ${di}`,dv="values(:'draft',gen_random_uuid(),:'key','UNDER_REVIEW'",dvp="values(:'draft',(select id from cert_packet),:'key','UNDER_REVIEW'";if(!g.includes(di)||!g.includes(dv))throw new Error('Certification runner WA fixture signature changed; refusing unsafe runtime rewrite');g=g.split(di).join(dip).split(dv).join(dvp);
const bi='insert into public.sales_order_drafts(id,packet_id,extraction_request_key,status,company_id,readiness_overall_score,readiness_dimensions,original_whatsapp_text)',bip=`with cert_contact as (insert into public.whatsapp_contacts(phone_number) values (substr(md5(:'draft'),1,20)) returning id),\n       cert_packet as (insert into public.whatsapp_message_packets(contact_id,stitched_content,first_message_at,last_message_at) select id,'{}'::jsonb,now(),now() from cert_contact returning id)\n       ${bi}`;if(!g.includes(bi))throw new Error('Certification runner invalid-WA fixture signature changed; refusing unsafe runtime rewrite');g=g.replace(bi,bip);
const oa='assert(attempts.every(x => x.ok && Array.isArray(x.data) && x.data.length === 1), `WA contention round ${round} had failed responses`);',na='assert(attempts.every(x => x.ok && Array.isArray(x.data) && x.data.length === 1), `WA contention round ${round} had failed responses: ${JSON.stringify(attempts.map(x => ({ok:x.ok,status:x.status,data:x.data})))}`);';if(!g.includes(oa))throw new Error('Certification runner contention assertion signature changed');g=g.replace(oa,na);writeFileSync(generatedRunner,g,{mode:0o600});}
if(process.argv.includes('--self-test')){selfTest();process.exit(0);}const dbUrl=process.env.SUPABASE_DB_URL??'';prepareIsolatedRunner();const result=spawnSync(process.execPath,[generatedRunner],{env:process.env,encoding:'utf8',stdio:['ignore','pipe','pipe']});sanitizeTree(outDir,dbUrl);assertNoSecret(outDir,dbUrl);if(result.stdout)process.stdout.write(redact(result.stdout,dbUrl));if(result.stderr)process.stderr.write(redact(result.stderr,dbUrl));if(result.error)process.stderr.write(`${redact(result.error.message,dbUrl)}\n`);if(result.status!==0){console.error(`Step 1 staging certification failed with exit code ${result.status??1}; credentials redacted.`);process.exit(result.status??1);}console.log('PASS: certification process-boundary credential redaction verified');
